### ISSUE TITLE
Model weights are not installed with the package

### ISSUE THREAD

**Issue by jtorhoff** [privML/privacy-evaluator#121]
If I try to load a pre-trained model I get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/privacy_evaluator/models/torch/dcti/model/model.pth'
```

`setup.py` actually doesn't copy the file over. 

Possible solutions on [StackOverflow](https://stackoverflow.com/questions/1612733/including-non-python-files-with-setup-py). I'll work on a fix.

**Comment by marisanest** [comment]
I have now the same problem with using the notebooks and installing our package within Colab. We could also ask @fraboeni if there is a possibility to save the models somewhere else permanently so that we can simply download our models from there.

**Comment by marisanest** [comment]
I asked @fraboeni via Gitter and also assigned her here to this issue, so maybe she will see it.

**Comment by marisanest** [comment]
I am currently on it and according to this guide [using-manifest-in](https://packaging.python.org/guides/using-manifest-in/) it seams that we need a MANIFEST.in file. I will try to fix it. I also need this for issue #114.

**Comment by marisanest** [comment]
Ok, I think I solved it via the `MANIFEST.in` file. @jtorhoff can you try out if it also works for you? The working branch is [114-installation-guide](https://github.com/privML/privacy-evaluator/tree/doc/114-installation-guide).

**Comment by jtorhoff** [comment]
Works like a charm, thanks for the fix!

**Comment by marisanest** [comment]
Perfect :+1:

**Comment by marisanest** [comment]
It's solved, so I will close this issue.
