### ISSUE TITLE
Simplify unit-tests

### ISSUE THREAD

**Issue by jtorhoff** [privML/privacy-evaluator#146]
Some tests are computationally intensive which is not necessary. In many cases we load the whole CIFAR10 dataset but the unit test itself doesn't really need it. 

I suggest we simplify some tests by not loading the whole dataset where it's not necessary to improve our CI checks running times.

I'll assign myself to do it for tests related to the work by team1 and we'd need someone from team2 to look into that as well.

**Comment by marisanest** [comment]
We should also consider loading data that is used by multiple tests only once. One way to do this could be to use fixtures. For example, at the moment multiple tests are loading the `CIFAR10` dataset and the `torch` model weights.

**Comment by jtorhoff** [comment]
> We should also consider loading data that is used by multiple tests only once. One way to do this could be to use `fixtures`. At the moment multiple tests are loading the `CIFAR10` dataset and the `torch` model weights. That should be changed.

Sounds good to me, I'll try to do that. I was first thinking of adding an argument to the `numpy` method which would tell it to e.g. only load the 10% or any other percentage of the dataset but your suggestion sounds more clean.

**Comment by marisanest** [comment]
I think your idea is also pretty good. I would even prefer to have a parameter for the `numpy` method (could be also used in other contexts such as the notebooks). And you can still use fixtures if needed :v:
