### ISSUE TITLE
Improve notebooks for non-expert users

### ISSUE THREAD

**Issue by Erdnaf** [privML/privacy-evaluator#154]
- Make sure that it is always clear which model is being loaded and which is being used to attack. 

- Have one notebook for each attack.

- Have interpretation of output in a notebook. (Improvement: include it in our library)

**Comment by Friedrich-Mueller** [comment]
Hey, I included the interpretations into the library. It would be nice if someone would have a look in regards to the selected files in which they occur as well as their format.

**Comment by Friedrich-Mueller** [comment]
Further improvements regarding the Zalando feedback are open todo, but I think we should make a new issue for that. So closing this for now.
