### ISSUE TITLE
Compare advantages and test on whole set

### ISSUE THREAD

**Issue by Erdnaf** [privML/privacy-evaluator#155]
Compare our vs tensorflow advantages for the same model, in order to make sure very small numbers are reasonable. 

Test our code on the whole dataset and not only 100 datapoints.

**Comment by jtorhoff** [comment]
It was due to ART returning labels instead of confidence scores. It is now fixed with the new version, although the advantage score for the rule-based attack doesn't make sense still because there we still have zeroes and ones.
