### ISSUE TITLE
Specify force-cpu as a variable

### ISSUE THREAD

**Issue by Erdnaf** [privML/privacy-evaluator#156]

**Comment by jtorhoff** [comment]
It's already possible for the PyTorch model: `torch_dcti.load_dcti(torch.device("cpu"))`.
For TensorFlow, it's possible by setting `tf.config.set_visible_devices([], 'GPU')` (works globally). 
Not sure if it's possible to apply for individual tensors and models with TF.

@blauertee Can you try the loading the PyTorch dcti model with device set to cpu, do you still get out of memory errors?

**Comment by blauertee** [comment]
Note from Franziska: Document how to set that for tf and pytorch in the readme
