### ISSUE TITLE
Creating Interface Classes

### ISSUE THREAD

**Issue by blauertee** [privML/privacy-evaluator#17]
Code interface classes according to the discussion we had in #5. 

The following image is just a sketch, to start the discussion and can be refined during coding.

![](https://user-images.githubusercontent.com/64256710/116098199-27115d80-a6ab-11eb-8c17-b3884d95a05f.png)

We decided to write wrapper classes instead of directly inheriting from [ART](https://github.com/Trusted-AI/adversarial-robustness-toolbox/) classes. 

We will have one class that manages all the attack classes, their execution and their result metrics, how exactly these things are managed is up for discussion.
And one class for each attack that inherits from a general attack interface class. Also what methods and attributes attack classes have to have is still up for discussion.

**Comment by Erdnaf** [comment]
@highclassfella i created a first draft of the interface. i tried to use formal interfaces as described here https://realpython.com/python-interface/

the tests have to be refined, but i have trouble to run the code
