### ISSUE TITLE
Improve output plots 

### ISSUE THREAD

**Issue by Friedrich-Mueller** [privML/privacy-evaluator#198]
* top 50 points per label ->top 50 points
* Can I get privacy risk scores for individual data points?
* Add more detailed explanations and examples to the notebooks/docstings.

**Comment by Erdnaf** [comment]
@Friedrich-Mueller Can this issue be closed? are the last two bulletpoints implemented?

**Comment by Friedrich-Mueller** [comment]
> 
> 
> @Friedrich-Mueller Can this issue be closed? are the last two bulletpoints implemented?

Im not sure. I'm not assigned to this :)

**Comment by Erdnaf** [comment]
Okay i chacked, this issue will be closed when #230 is merged
