### ISSUE TITLE
Documentation fix -- contradictory explanation

### ISSUE THREAD

**Issue by yzchyx** [privML/privacy-evaluator#233]
In the documentation/naming of `ratios_for_attack` in the notebook, the given ratios of the example target model is `0.66: {0: 1000, 1: 500}`: 33% of data points are from class 0, 66% from class 1.) , which is confusing because the distribution of the two classes are opposite

**Comment by InaFen** [comment]
I changed the notebook accordingly, now the target model has {0: 500, 1: 1000}
