### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by budmil** [privML/privacy-evaluator#39]
Do this for automated testing and checking style via black.

**Comment by Erdnaf** [comment]
This is someting I found regarding the test automation for pytest https://www.europeclouds.com/blog/test-automation-how-to-build-a-ci-cd-pipeline-using-pytest-and-github-actions

**Comment by budmil** [comment]
@Erdnaf @marisanest please take a look at the corresponding PR that I opened. The problem I see is that we can't actually test this until we merge it into main, but not sure.
