### ISSUE TITLE
Improve accuracy metrics

### ISSUE THREAD

**Issue by budmil** [privML/privacy-evaluator#40]
Fix typos (language-wise content) in function documentation.
Change the name of functions themselves to train_to_test_ratio/difference (or train_test_gap)

**Comment by budmil** [comment]
I think we can close this Issue? @marisanest

**Comment by marisanest** [comment]
Yes, will be closed by PR #51.

**Comment by marisanest** [comment]
Solved by PR #51

**Comment by marisanest** [comment]
Solved by PR #51
