### ISSUE TITLE
Read the Membership Inference paper again and have a look at the MIA Example Notebook provided by Franziska

### ISSUE THREAD

**Issue by Friedrich-Mueller** [privML/privacy-evaluator#52]
https://arxiv.org/pdf/1610.05820v2.pdf
https://arxiv.org/abs/2003.10595, implementation: [tensorflow](https://github.com/tensorflow/privacy/blob/452873e9ce471346ff6faadf5f930a03a6f1fbfe/tensorflow_privacy/privacy/membership_inference_attack/membership_inference_attack.py#L220)

**Comment by budmil** [comment]
Here's a talk of MIA paper author about it, much more understandable as a whole than the paper itself: https://www.youtube.com/watch?v=rDm1n2gceJY

**Comment by marisanest** [comment]
I think we are done with this issue so I will close it.
