### ISSUE TITLE
Save the models

### ISSUE THREAD

**Issue by mariesig** [privML/privacy-evaluator#58]
-Models created last week with Pytorch and Tensorflow with Cifar10 have to be saved
-create folder structure,
example name : PyTorch/Tensorflow_pretrainedResNet50_class1_ratio_class2 _ratio
- create Dopboxaccount & save the models there
- create link to dropbox in GitHub , separate README for Property Inference Attack

**Comment by yzchyx** [comment]
Hi, we have saved the models as follows:

<img src="https://user-images.githubusercontent.com/42862848/118796603-0d26fd00-b89c-11eb-8183-e22a7e2f649d.png" alt="drawing" width="600"/>

The naming of the models is: The first word (tf for TensorFlow and torch for PyTorch) implies the framework, the second word "pt" means we used pretrained weights, the third word is the name of the model, and the rest words are the `class_id` and `num_samples` pairs.

Here is the [shared link](https://www.dropbox.com/sh/299cmfus7lafigs/AAAb10rhHwIU7wL7u6kkvxXEa?dl=0).

We will add it to README after the separate README for Property Inference Attack is done by our team (Team 2).
