### ISSUE TITLE
Create membership inference score, just as it is in Tensorflow privacy

### ISSUE THREAD

**Issue by Friedrich-Mueller** [privML/privacy-evaluator#78]
See https://arxiv.org/pdf/2003.10595.pdf

Acceptance criteria:
- Implements the score as described in the paper
- Allows slicing according to the classes
- Allows slicing according to the correctly or wrongly classified data-points

**Comment by marisanest** [comment]
I found another paper: https://arxiv.org/abs/1712.09136. It is referenced here: [adversarial-robustness-toolbox](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/ba8f84006aaa9cfc81bf9cc4d8c1642a4eacd507/art/metrics/privacy/membership_leakage.py#L43).

**Comment by jtorhoff** [comment]
Here's how they do it in TF privacy: [_compute_membership_probability](https://github.com/tensorflow/privacy/blob/331a2911ac3cdf1d9d8d301813be3541257d5bf4/tensorflow_privacy/privacy/membership_inference_attack/membership_inference_attack.py#L217) (the paper is referenced there).

The description makes sense:

> For an individual sample, its privacy risk score is computed as the posterior  probability of being in the training set  after observing its prediction output by the target machine learning model.

But I don't quite follow the code and the use of histogram.

**Comment by jtorhoff** [comment]
I also found the code published by the authors of the paper [here](https://github.com/inspire-group/membership-inference-evaluation/blob/master/privacy_risk_score_utils.py)
