### ISSUE TITLE
Rename and Improve model_card_info method

### ISSUE THREAD

**Issue by budmil** [privML/privacy-evaluator#81]
- Rename mode_card_info
- Add try catches to the model_card_info output
- Current output all floats – look into json output format
- Method to convert output to json, 

Columns in the model card info output are fixed/static – every model would get those 5 attributes
Might make sense to deduce the dict keys from the data

Output should be human readable.

**Comment by Erdnaf** [comment]
https://pythonexamples.org/convert-python-class-object-to-json/
