### ISSUE TITLE
Calculate train-test gap

### ISSUE THREAD

**Issue by budmil** [privML/privacy-evaluator#9]
metric 1 = train acc - test acc
metric 2 = train acc / test acc

### Acceptance criteria
calculated correctly
output in a programatically extractable format

**Comment by marisanest** [comment]
Branch: [feat/9-train-test-gap-calculation](privML/privacy-evaluator/tree/feat/9-train-test-gap-calculation)

**Comment by marisanest** [comment]
Hey @fraboeni, just to make things clear. For this task to be accepted, we do not need to calculate the test and train accuracy by our own (they are given). We only have to take the accuracies and return the wanted measures, right?
